"""
src/evaluate.py
Evaluation metrics for AdvShield-Med.

Two evaluation modes:
  1. Classification metrics   — for diagnostic model (accuracy, precision, recall, F1)
  2. Detection metrics        — for gatekeeper (same metrics, different interpretation)

Both tasks are binary so the same functions serve both, but labelled separately
in notebooks for clarity.

Usage:
    from src.evaluate import evaluate_model, print_report

    metrics = evaluate_model(model, test_loader, device)
    print_report(metrics, title="Gatekeeper — PGD (unseen)")
"""

from typing import Dict

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
)


# ──────────────────────────────────────────────
# Core evaluation
# ──────────────────────────────────────────────
def evaluate_model(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device = None,
    positive_label: int = 1,
) -> Dict[str, float]:
    """
    Run inference over a DataLoader and compute binary classification metrics.

    Args:
        model: nn.Module in eval mode (or will be set to eval)
        loader: DataLoader yielding (images, labels)
        device: target device (auto-detected if None)
        positive_label: the class index treated as "positive" for
                        precision/recall/F1 (default 1)

    Returns:
        dict with keys:
            accuracy, precision, recall, f1,
            confusion_matrix (2×2 np.array),
            all_preds (np.array), all_labels (np.array)
    """
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model.eval()
    model = model.to(device)

    all_preds = []
    all_labels = []

    with torch.no_grad():
        for images, labels in loader:
            images = images.to(device, non_blocking=True)
            logits = model(images)
            preds = logits.argmax(dim=1).cpu().numpy()
            all_preds.extend(preds)
            all_labels.extend(labels.numpy())

    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)

    return {
        "accuracy":         accuracy_score(all_labels, all_preds),
        "precision":        precision_score(all_labels, all_preds, pos_label=positive_label, zero_division=0),
        "recall":           recall_score(all_labels, all_preds, pos_label=positive_label, zero_division=0),
        "f1":               f1_score(all_labels, all_preds, pos_label=positive_label, zero_division=0),
        "confusion_matrix": confusion_matrix(all_labels, all_preds, labels=[0, 1]),
        "all_preds":        all_preds,
        "all_labels":       all_labels,
    }


def evaluate_model_at_epsilon(
    model: nn.Module,
    attacked_loader: DataLoader,
    device: torch.device = None,
) -> Dict[str, float]:
    """
    Alias of evaluate_model for clarity when reporting accuracy-under-attack.

    The attacked_loader should yield pre-computed adversarial images
    (already generated by src/attacks.py and saved to disk).

    Returns same dict as evaluate_model.
    """
    return evaluate_model(model, attacked_loader, device)


# ──────────────────────────────────────────────
# Reporting
# ──────────────────────────────────────────────
def print_report(metrics: Dict, title: str = "") -> None:
    """
    Pretty-print a metrics dict returned by evaluate_model.

    Args:
        metrics: dict from evaluate_model()
        title: optional label (e.g., "Gatekeeper — FGSM (seen)")
    """
    header = f"  {title}  " if title else ""
    sep = "─" * max(50, len(header) + 4)

    print(f"\n{sep}")
    if title:
        print(f"  {title}")
        print(sep)

    print(f"  Accuracy:  {metrics['accuracy']:.4f}  ({metrics['accuracy']*100:.1f}%)")
    print(f"  Precision: {metrics['precision']:.4f}")
    print(f"  Recall:    {metrics['recall']:.4f}")
    print(f"  F1 Score:  {metrics['f1']:.4f}")

    cm = metrics["confusion_matrix"]
    print(f"\n  Confusion Matrix:")
    print(f"              Pred 0  Pred 1")
    print(f"  Actual 0:   {cm[0,0]:>6}  {cm[0,1]:>6}")
    print(f"  Actual 1:   {cm[1,0]:>6}  {cm[1,1]:>6}")
    print(sep)


def build_results_row(
    label: str,
    metrics: Dict,
) -> Dict[str, str]:
    """
    Format a metrics dict into a flat dict suitable for a results CSV row
    or pandas DataFrame row.

    Args:
        label: row label (e.g., "Gatekeeper — PGD (unseen)")
        metrics: dict from evaluate_model()

    Returns:
        flat dict: {label, accuracy, precision, recall, f1}
    """
    return {
        "label":     label,
        "accuracy":  f"{metrics['accuracy']:.4f}",
        "precision": f"{metrics['precision']:.4f}",
        "recall":    f"{metrics['recall']:.4f}",
        "f1":        f"{metrics['f1']:.4f}",
    }
